name: Python CI

on:
  push:
    branches:
      - main  # Runs the workflow when you push to 'main' branch
  pull_request:
    branches:
      - main  # Runs when a PR is opened to 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # The machine where the tests will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
