name: Auto-Deploy & Monitor

on:
  push:
    branches:
      - main  # Runs on every push to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Start Application
        run: nohup python Gif-by-Python.py > output.log 2>&1 &

      - name: Check If App is Running
        run: ps aux | grep python
      - name: Capture Logs
        run: cat output.log || echo "No logs found"
    
      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v3
        with:
  name: application-logs
       path: output.log
     - name: Check Running Processes
       run: ps aux | grep python
     - name: Monitor System Usage
       run: |
       echo "Memory Usage:"
       free -m
       echo "CPU Usage:"
       top -b -n1 | head -n 10
